### ISSUE TITLE
tag for version 5.0

### ISSUE THREAD

**Issue by rolandlo** [benini/scid#102]
Has Scid 5.0 been released? It looks so from https://sourceforge.net/projects/scid/files/Scid/Scid%205.0/ and https://github.com/benini/scid/commits/github
However there is no v5.0.0 tag (see https://github.com/benini/scid/tags), which is confusing. For updating the flatpak a tag would be needed.

**Comment by benini** [comment]
Thanks, I have released the 5.0.0 version an updated the flatpak manifest.
Please let me know if everything is ok.

**Comment by rolandlo** [comment]
It looks fine. If you create a PR for the updated flatpak manifest (with removed icon, desktop and metadata file) on the flathub/io.github.benini.scid repository, we can check out the automatic build.

**Comment by benini** [comment]
I'm thinking about adding the scid_extra.zip package (https://sourceforge.net/projects/scid/files/Scid/Scid%20Latest/) using extra-data. It should be enough to download the package and decompress it in the /app/scid/scid folder.
What's you opinion?

**Comment by rolandlo** [comment]
The content of scid_extra.zip looks fine. However I don't think you need to use `extra-data`. The `extra-data` option (as I understand) was designed to include proprietary software without redistributing it. 
Just use a source of type "archive" and move it to the right place using the `install` command with the `-t` option like
```yaml
- name: scid-extra
  buildsystem: simple
  build-commands: 
    - install -D ./* -t /app/scid/scid
  sources:
  - type: archive
    url: https://sourceforge.net/projects/scid/files/Scid/Scid%20Latest/scid_extra.zip
  - sha256: 0175c80da101278b20628ca70670a93b2d90129e
```
I haven't tested it, but at least that's the way I would try it.
